from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas
from pathlib import Path


class PDFService:

    def generate_pdf(self, lc_number):

        output_dir = Path("generated/pdf")
        output_dir.mkdir(parents=True, exist_ok=True)

        pdf_path = output_dir / f"{lc_number}.pdf"

        c = canvas.Canvas(str(pdf_path), pagesize=A4)

        c.setFont("Helvetica-Bold", 18)
        c.drawString(50, 800, "LETTER OF CREDIT")

        c.setFont("Helvetica", 12)
        c.drawString(50, 760, f"LC Number : {lc_number}")

        c.drawString(50, 730, "Generated by ALCOS")

        c.save()

        return pdf_path